dist: trusty
language: rust
services: docker
sudo: required

addons:
  postgresql: "9.5"

matrix:
  include:
    # Rust stable
    - rust: stable
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PG_USER=postgres
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"
    - os: osx
      rust: stable
      env:
      - TARGET=x86_64-apple-darwin
      - PG_USER=travis
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"

    # Rust beta
    - rust: beta
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PG_USER=postgres
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"

    # Rust nightly
    - rust: nightly
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PG_USER=postgres
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"

  allow_failures:
    # Rust nightly
    - rust: nightly
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PG_USER=postgres
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"

env:
  global:
    - RUST_BACKTRACE=1

before_script: ./ci/before_script.sh
script: cargo test --features=test-suite

cache:
  directories:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
on_success: never