dist: trusty
language: rust
services: docker
sudo: required

addons:
  postgresql: "9.5"
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev

matrix:
  include:
    # Rust stable
    - rust: stable
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PKG_CONFIG_PATH=/usr/lib/pkgconfig:$PKG_CONFIG_PATH
      - PG_USER=postgres
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"
      - PATH=$HOME/.local/bin:$PATH
    - os: osx
      rust: stable
      env:
      - TARGET=x86_64-apple-darwin
      - PG_USER=travis
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"
      - PATH=$HOME/Library/Python/2.7/bin:$PATH

    # Rust beta
    - rust: beta
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PKG_CONFIG_PATH=/usr/lib/pkgconfig:$PKG_CONFIG_PATH
      - PG_USER=postgres
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"
      - PATH=$HOME/.local/bin:$PATH

    # Rust nightly
    - rust: nightly
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PKG_CONFIG_PATH=/usr/lib/pkgconfig:$PKG_CONFIG_PATH
      - PG_USER=postgres
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"
      - PATH=$HOME/.local/bin:$PATH

  allow_failures:
    # Rust nightly
    - rust: nightly
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - PKG_CONFIG_PATH=/usr/lib/pkgconfig:$PKG_CONFIG_PATH
      - PG_USER=postgres
      - TEST_POSTGRES_URL="postgres://$PG_USER@localhost:5432/indradb_test"
      - PATH=$HOME/.local/bin:$PATH

env:
  global:
    - RUST_BACKTRACE=1

script:
  - source ~/.cargo/env || true
  - cargo test --features=test-suite

cache:
  directories:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
on_success: never